server:
  port: 8080

logging.file: logs/application.log
logging:
  level:
    org:
      springframework:
        web: DEBUG
spring:
  datasource:
    url: jdbc:h2:file:./h2-db/h2;MODE=Oracle
  h2:
    console:
      enabled: true
  flyway:
    baseline-on-migrate: true
    locations: "classpath:/db/migration"
#mybatis:
#  mapper-locations: "classpath:mapper/*Mapper.xml"
mybatis:
  mapper-locations: "classpath:mapper/*Mapper.xml"
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl