server:
  port: 8080

logging.file: logs/application.log
logging:
  level:
    org:
      springframework:
        web: DEBUG
spring:
  datasource:
    url:  jdbc:h2:mem:tws_persistence_db
  h2:
    console:
      enabled: true
#mybatis:
#  mapper-locations: "classpath:mapper/*Mapper.xml"
mybatis:
  mapper-locations: "classpath:mapper/*Mapper.xml"
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl